DEFAULT_SEMANTIC_PRODUCT_KNOWLEDGE = [
    {
        "product_name": "Savings Account",
        "aliases": ["savings account", "saving account", "bank account"],
        "category": "banking_service",
        "use_cases": ["liquidity", "salary credit", "emergency fund parking", "digital banking access"],
        "suitable_for": ["basic banking", "emergency fund", "cash flow management"],
        "adoption_guidance": "Use as the base account for digital banking, savings discipline, and emergency liquidity.",
        "risk_notes": "Low risk, but customer should follow safe banking practices.",
        "source_basis": "Official SBI personal banking deposit knowledge",
    },
    {
        "product_name": "Recurring Deposit",
        "aliases": ["recurring deposit", "rd"],
        "category": "deposit",
        "use_cases": ["monthly savings", "short-term goals", "emergency fund building", "down payment planning"],
        "suitable_for": ["regular income customers", "savings habit", "goal-based accumulation"],
        "adoption_guidance": "Use when the customer has monthly surplus and needs disciplined recurring savings.",
        "risk_notes": "Low market risk; premature closure and interest rules should be checked before adoption.",
        "source_basis": "Official SBI recurring deposit knowledge",
    },
    {
        "product_name": "Fixed Deposit",
        "aliases": ["fixed deposit", "fd", "term deposit"],
        "category": "deposit",
        "use_cases": ["capital protection", "lump-sum parking", "emergency reserve strengthening"],
        "suitable_for": ["conservative risk preference", "idle savings", "short to medium-term parking"],
        "adoption_guidance": "Use for customers who prefer capital protection and have lump-sum savings.",
        "risk_notes": "Low market risk; liquidity and premature withdrawal rules should be understood.",
        "source_basis": "Official SBI fixed deposit knowledge",
    },
    {
        "product_name": "Tax Saving Deposit",
        "aliases": ["tax saving deposit", "tax saver fd", "tax saving fixed deposit"],
        "category": "tax_saving",
        "use_cases": ["tax saving", "capital protection", "fixed-return planning"],
        "suitable_for": ["tax-saving goal", "conservative risk preference"],
        "adoption_guidance": "Use only when customer has tax-saving intent and understands lock-in conditions.",
        "risk_notes": "Lock-in and tax rules must be reviewed before adoption.",
        "source_basis": "Official SBI tax-saving deposit knowledge",
    },
    {
        "product_name": "Public Provident Fund",
        "aliases": ["ppf", "public provident fund"],
        "category": "long_term_savings",
        "use_cases": ["long-term savings", "retirement planning", "tax-aware savings"],
        "suitable_for": ["long-term goals", "conservative customers", "retirement planning"],
        "adoption_guidance": "Use for long-term disciplined savings where lock-in is acceptable.",
        "risk_notes": "Long lock-in; customer should understand liquidity limits.",
        "source_basis": "Official SBI PPF account knowledge",
    },
    {
        "product_name": "SIP / Investment Services",
        "aliases": ["sip", "systematic investment plan", "investment services"],
        "category": "investment",
        "use_cases": ["wealth creation", "long-term goals", "retirement corpus", "child education corpus"],
        "suitable_for": ["moderate risk", "aggressive risk", "long investment horizon"],
        "adoption_guidance": "Use only after basic emergency fund and protection needs are considered.",
        "risk_notes": "Market-linked; customer must understand risk-return tradeoff.",
        "source_basis": "SBI Mutual Fund and SEBI investor education knowledge",
    },
    {
        "product_name": "Mutual Fund Investment Services",
        "aliases": ["mutual fund", "mutual funds", "mf"],
        "category": "investment",
        "use_cases": ["wealth creation", "goal-based investing", "portfolio diversification"],
        "suitable_for": ["moderate risk", "aggressive risk", "long-term goals"],
        "adoption_guidance": "Use when customer has investment readiness and understands market risk.",
        "risk_notes": "Returns are not guaranteed and depend on market performance.",
        "source_basis": "SBI Mutual Fund and SEBI investor education knowledge",
    },
    {
        "product_name": "SBI Insurance Services",
        "aliases": ["insurance", "life insurance", "health insurance", "protection planning"],
        "category": "protection",
        "use_cases": ["family protection", "health protection", "risk transfer"],
        "suitable_for": ["married customers", "dependents", "no insurance coverage", "family responsibility"],
        "adoption_guidance": "Use before aggressive wealth creation if protection gap exists.",
        "risk_notes": "Customer should understand coverage, exclusions, premium, and policy terms.",
        "source_basis": "SBI insurance ecosystem and IRDAI policyholder awareness knowledge",
    },
    {
        "product_name": "Home Loan Readiness Journey",
        "aliases": ["home loan", "home purchase", "home loan readiness"],
        "category": "loan_readiness",
        "use_cases": ["home purchase", "down payment planning", "loan eligibility preparation"],
        "suitable_for": ["home purchase goal", "stable income customers"],
        "adoption_guidance": "Use after assessing down payment readiness, income stability, and repayment capacity.",
        "risk_notes": "Customer should understand EMI responsibility, interest rate type, tenure, and affordability.",
        "source_basis": "Official SBI home loan knowledge",
    },
    {
        "product_name": "YONO Digital Banking Journey",
        "aliases": ["yono", "digital banking", "mobile banking", "internet banking"],
        "category": "digital_adoption",
        "use_cases": ["digital onboarding", "account access", "service adoption", "guided banking actions"],
        "suitable_for": ["all customers using digital SBI services"],
        "adoption_guidance": "Use as the digital channel for guided adoption of relevant SBI services.",
        "risk_notes": "Customer should follow safe digital banking practices and never share credentials or OTP.",
        "source_basis": "Official SBI digital banking knowledge",
    },
    {
        "product_name": "Safe Banking Awareness Journey",
        "aliases": ["safe banking", "fraud awareness", "security awareness"],
        "category": "safety",
        "use_cases": ["fraud prevention", "mis-selling awareness", "digital safety"],
        "suitable_for": ["all customers"],
        "adoption_guidance": "Show safety nudges whenever financial products or digital journeys are recommended.",
        "risk_notes": "Customer must verify product details and avoid sharing sensitive credentials.",
        "source_basis": "RBI financial education and SBI safe banking awareness knowledge",
    },
]